name: Storybook Build & Deploy
on:
  pull_request:
    branches: [documentation]
  push:
    branches: [documentation]

jobs:
  build-and-deploy:
    name: Publish Master Storybook 📕
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          persist-credentials: false
      - name: Install and Deploy 🚀
        run: | # Install npm packages and Deploy the Storybook files
          yarn install
          yarn run deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
